### ISSUE TITLE
Adding tasks to Gantt chart breaks cell alignment

### ISSUE THREAD

**Issue by darthtang** [haris-raheem/SuiteCRM#1]
Hi Haris, you are already familiar with this bug via a previous email I had sent.

This seems to be bug whilst using chrome

![image](https://cloud.githubusercontent.com/assets/6104874/17049941/28a2dbb6-4fe8-11e6-84ea-dd4941f45995.png)

Thanks 

Darren

**Comment by haris-raheem** [comment]
Please confirm if on chrome, you ever see the task spread across more than one cell. my observation is that on chrome no task on gantt will cover more than one cell.

**Comment by haris-raheem** [comment]
Fixed, i have committed the code. it was an css issue specific to chrome

**Comment by darthtang** [comment]
Fantastic Haris! Seems to be fixed now
