### ISSUE TITLE
Business Hours 'Hours' are 1 hour short.

### ISSUE THREAD

**Issue by darthtang** [haris-raheem/SuiteCRM#2]
The Business Hours option is working fine for days as you can see in in the 2nd screen shot. Please note my business hours are 9-10 am(Monday-Friday)

![image](https://cloud.githubusercontent.com/assets/6104874/17050470/ec996790-4fea-11e6-85d6-d6f18fce743a.png)

![image](https://cloud.githubusercontent.com/assets/6104874/17050460/df9b99d2-4fea-11e6-83a7-a93b1506bb2d.png)

The first 3 tasks i was testing the days and it works as it should.

The last task is 5 hours but only runs from Monday - Thursday. It should be onto and including the 5th hour (which would be on the friday)

**Comment by haris-raheem** [comment]
Fixed and committed the change.

**Comment by darthtang** [comment]
Fix confirmed, great work!
