### ISSUE TITLE
Unable to add new task on Gantt view

### ISSUE THREAD

**Issue by darthtang** [haris-raheem/SuiteCRM#3]
HI Haris,

As before this is a highlighted on the PDF i sent to you, here is just the GITHUB version of it.

Creating an empty project template, then navigating away from the record, then navigate back into the Gantt view to create a task, unable to do so.

![image](https://cloud.githubusercontent.com/assets/6104874/17059306/702db36e-501c-11e6-8144-03eb5010c25a.png)

This seems to happen only on Project Templates.

Thanks

Darren

**Comment by haris-raheem** [comment]
Fixed and committed. hopefully you won't get this issue anymore.
it was a JS loading related issue.

**Comment by darthtang** [comment]
Fix confirmed, able to create tasks, Thanks
